### ISSUE TITLE
Polish translation cooridnation

### ISSUE THREAD

**Issue by FoxoBread** [Yellow-Dog-Man/Locale#116]
As seen in #109, #113, and now my #115; there's a bit of a doozy with the Polish translations.
There's a few strings where the technical terminology should be discussed to maintain accuracy within correct contexts. 

@AdamK2003 has fixed some spelling and grammar issues (#113) which should be merged first while the remaining strings which all three of us translated will need to be agreed upon.

**Comment by Alex-2Pi** [comment]
As in our private conversation, I agree with the merged request #113 .

In such a case, it seems to me that our merged request makes no sense.
I don't know how it usually works, I guess we should just start working on what will be left after his merged request.

**Comment by FoxoBread** [comment]
Indeed, however there is a few bits of terminology that I feel should be discussed and more opinions be brought along.


An example is: `"Inspector.VHACD.Parameter.MaxVerticesPerHull": "Maks. wierzchołków na strukturę"`

Where the word "hull" doesn't really have a good translation (unless "otoczka" is indeed the correct technical term), and thus a more general word might be a better option.

**Comment by AdamK2003** [comment]
I'm actually not 100% sure what the actual technical term is either, "otoczka" probably ain't it, but I didn't have any better ideas and that was the best word I could get out of deepl.

**Comment by FoxoBread** [comment]
Yeah I figured the layman approach might be more appropriate given Polish is a little behind with technical terms...

**Comment by FoxoBread** [comment]
I'm working on merging our work [into one branch](https://github.com/FoxoBread/Locale/commit/fcc32e3911fd3b11e2b9c6c51d19ec12bf7b662d), what are we thinking in terms of our translations for the login and registration strings?

**Comment by AdamK2003** [comment]
Just updated my repo (and PR); replaced `otoczka` with `powłoka` and fixed a few other things I noticed. I'll probably make another proper pass and maybe get the branches figured out later.

**Comment by FoxoBread** [comment]
Good call, I think "powłoka" is the best we're gonna get.

"kadłub" is only really used in context of air/naval craft to describe the vessel's structure.

In terms of the login strings and such, there's some nuances I touched up in my PR that I think make it a little less clunky; "Nie pamiętasz hasła?" being used instead of "Zgubione Hasło?" but they're not perfect in some cases.

**Comment by AdamK2003** [comment]
I just draft'd that PR and pushed the English fixes separately.

Also: seems like we have some stuff to update too, there's some new placeholders (for the support and moderation URLs) after today's update.

**Comment by Alex-2Pi** [comment]
Yes, they changed it a bit

**Comment by FoxoBread** [comment]
Which lines are you referencing exactly?

**Comment by AdamK2003** [comment]
Everything that includes `support.resonite.com` or `moderation.resonite.com`; gotta replace those with `{supportUrl}` and `{moderationUrl}` respectively. Should be a simple search and ~~destroy~~replace.

**Comment by FoxoBread** [comment]
Gotcha, I thought you meant they were new which confused me as I wrote those strings in Polish a few days ago xD
Should I update my fork so we can agree upon and squash conflicts?

**Comment by AdamK2003** [comment]
Yeah, they're just new placeholders, there's no actual new strings or anything; and yep, you can definitely update your forks.

**Comment by FoxoBread** [comment]
I've updated my fork to include the new placeholders, fixes and combined translations with consideration to grammar, language and context.
