### ISSUE TITLE
"UI.VideoPlayer.BroascastAudio" locale key

### ISSUE THREAD

**Issue by XDelta** [Yellow-Dog-Man/Locale#12]
Should be "UI.VideoPlayer.BroadcastAudio".

**Comment by ProbablePrime** [comment]
Hey @RyuviTheViali , Can you see if this spelling mistake is also in the actual video player?

**Comment by RyuviTheViali** [comment]
The string is misspelled in the video player, too. I'll adjust the video player's string so it can be corrected in locale.

**Comment by XDelta** [comment]
Appears to be fixed in the video player now and in the locale with #202.
