### ISSUE TITLE
English [en] still has "I am 13 years of age or older"

### ISSUE THREAD

**Issue by 39sStanislavskii** [Yellow-Dog-Man/Locale#14]
In en.json on 449 line 
"Account.AgeConfirm": "I am 13 years of age or older",
still has "i'm 13yo" confirmation text

**Comment by ProbablePrime** [comment]
Ahh this is now unused afaik. I will purge it.

**Comment by ProbablePrime** [comment]
I have removed this string from EN.

Feel free to remove it for other languages, but there is no need to rush it is not displayed anywhere.
