### ISSUE TITLE
unable to find source of what is driving a blend shape

### ISSUE THREAD

**Issue by aecii** [Yellow-Dog-Man/Locale#152]
When you load an avatar, and notice a blend shape is being driven there is no way (that I know of)  to see what is driving that specific blend shape.  

Create an avatar,  drive the blend using protoflux,  and try to find what is driving it without a mod.

**Comment by Stellanora64** [comment]
Please make the issue here: https://github.com/Yellow-Dog-Man/Resonite-Issues

This respiratory is for local issue

**Comment by aecii** [comment]
Opps. Relocating it.
