### ISSUE TITLE
Context of Contacts.Unblocked

### ISSUE THREAD

**Issue by FoxoBread** [Yellow-Dog-Man/Locale#156]
In which context is `Contacts.Unblocked` used in?
Pressing that button will block/unblock the contact or does it simply state they are not blocked?

**Comment by Frooxius** [comment]
Both. There's a list of states of the contact that they can be in that are shown all at once. Clicking on the state will change them to that state.

**Comment by FoxoBread** [comment]
Gotcha, thanks!
