### ISSUE TITLE
Localization for date and time notation of Main UI Panel in Cloud Home

### ISSUE THREAD

**Issue by Zozokasu** [Yellow-Dog-Man/Locale#17]
今現在、CloudHomeにあるMain UI Panelにあるは、例えば日付の場合「ddd, MMM DD,yyyy」のようにハードコーディングされています。しかしながら、これは言語によって変えられるようにすべきであると思います。
例えば日本語の場合、「yyyy年 MM月 dd日 ddd曜日」、「tt h時mm分ss秒」など。

Currently, the DateTimeTextDriver in the Main UI Panel of CloudHome is hard-coded as "ddd, MMM DD,yyyy" for dates, but it would be more appropriate if the date and time in this panel could be changed according to language.
For example, "yyyy年 MM月 dd日 ddd曜日" ,"tt h時mm分ss秒"in Japanese, etc.

**Comment by ProbablePrime** [comment]
This will now be solved by prime's information in https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/185

So i'll move the convo there.
