### ISSUE TITLE
Some text used in StaticTexture's inspector does not have translation keys

### ISSUE THREAD

**Issue by eai04191** [Yellow-Dog-Man/Locale#172]
At the bottom of the StaticTexture2D component:
![image](https://github.com/Yellow-Dog-Man/Locale/assets/3516343/1b85c377-adf2-48db-a6bf-526cb9d134dd)

The translation keys used in `Inspector.Texture.AdjustAlphaGamma` and `Inspector.Texture.AddAlpha` are not defined in the locale file. Keys remain visible in any language setting

**Comment by stiefeljackal** [comment]
I didn't notice this issue was already posted. #401 resolved this for `en`, so you may close this @eai04191.
