### ISSUE TITLE
"World.Filter.MinimumFriends" locale key

### ISSUE THREAD

**Issue by Zozokasu** [Yellow-Dog-Man/Locale#20]
![image](https://github.com/Yellow-Dog-Man/Locale/assets/13605108/14f802a9-c1da-4050-bde9-440e4df9bd5d)

翻訳データにはそれらしい項目が確かに存在するが、アプリ内に反映されていない。（他の言語でも確認済み）

There are indeed items in the translation data that seem to be there, but they are not reflected in the application. (Confirmed in other languages as well.)

**Comment by jojo3926** [comment]
![image](https://github.com/Yellow-Dog-Man/Locale/assets/13605108/8d64e891-ca95-4157-88f6-06c9ee7c226d)
A similar glitch was found in the maximum access level option.
("LAN" is correct)

**Comment by ProbablePrime** [comment]
I've submitted some fixes here.

**Comment by ProbablePrime** [comment]
This should be resolved now, please re-open if not
