### ISSUE TITLE
Some keys in en.json have two entries in settings-overhaul branch

### ISSUE THREAD

**Issue by Muppeq** [Yellow-Dog-Man/Locale#212]
I remembered already having translated some strings but there were new entries in en.json that did not have a corresponding translation. At least these keys have two entries:

Settings.DebugSettings.DebugResetAllSimpleSettings
Settings.LegacyFeatureSettings.ConvertLegacySettings

(for commit 04e1194)

**Comment by shadowpanther** [comment]
These keys also have different values in two places:
https://github.com/Yellow-Dog-Man/Locale/blame/b80c94ba56a4cc88fbc1de814c14a809bd68f61b/en.json#L1186-L1187
https://github.com/Yellow-Dog-Man/Locale/blame/b80c94ba56a4cc88fbc1de814c14a809bd68f61b/en.json#L1324-L1328

**Comment by Muppeq** [comment]
This problem has now been fixed, the keys appear only once in the file.
