### ISSUE TITLE
Audio stream strings still used but removed from locale file

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/Locale#241]
To reproduce:
1. Set game to EN
2. Click on the audio stream facet
3. Observe strings missing

Tested on Beta 2024.4.16.520.

Probably due to: https://github.com/Yellow-Dog-Man/Locale/commit/20d8ca7623b6e322d1bad350c0c52727f8f27105

![Resonite_u7xihC9Fli](https://github.com/Yellow-Dog-Man/Locale/assets/76598503/8335f704-8cad-4993-a02a-5355e9cc5bf9)

**Comment by Banane9** [comment]
Just stumbled across this too and was worried I messed something up :'D

**Comment by Banane9** [comment]
Relevant comment from froox: https://github.com/Yellow-Dog-Man/Locale/pull/386#issuecomment-2189756531

**Comment by Banane9** [comment]
I released a mod on the Modding Discord which re-adds all the removed keys for the time being (doesn't pose any issue with newly added or modified keys): https://discord.com/channels/901126079857692714/1156659455929352234/1259614018016903330

**Comment by jae1911** [comment]
Closing this then.
