### ISSUE TITLE
Requesting for a translator badge

### ISSUE THREAD

**Issue by modimobeikete** [Yellow-Dog-Man/Locale#262]
I'm currently keep track on the zh-cn translation.I'd like to request for a translator badge for myself and my parther.
      My resonite username:modimobeikete
      Parther resonite username:WARCRAFT11

**Comment by jae1911** [comment]
From the wiki, no such badge currently exists (https://wiki.resonite.com/Badges).

Only translation-related badges were for MMC20, 22 and 23 for the Japanese translators.

**Comment by Frooxius** [comment]
Added badge to WARCRAFT11 as well. Thanks!
