### ISSUE TITLE
Height Locale Strings Removed, But Still Used for `Full Body / Avatar Calibration`

### ISSUE THREAD

**Issue by stiefeljackal** [Yellow-Dog-Man/Locale#270]
The `Settings.Height`, `Settings.Metric`, and `Settings.Imperial` locale keys were removed due to the transition from the old to the new settings Screen. However, these keys are still used for Full Body / Avatar Calibration.

<img width="332" alt="image" src="https://github.com/Yellow-Dog-Man/Locale/assets/20023996/312ff28b-14e0-4d80-9527-79d39a9fbbb2">

**Comment by FoxoBread** [comment]
I believe a similar problem plagues audio streaming also.

**Comment by Banane9** [comment]
I suppose froox's comment from #386 that they're "reworking" them would apply here too?
https://github.com/Yellow-Dog-Man/Locale/pull/386#issuecomment-2189756531

**Comment by FoxoBread** [comment]
Yes.

**Comment by Banane9** [comment]
I released a mod on the Modding Discord which re-adds all the removed keys for the time being (doesn't pose any issue with newly added or modified keys): https://discord.com/channels/901126079857692714/1156659455929352234/1259614018016903330

**Comment by stiefeljackal** [comment]
Fixed as of `2024.7.25.1115`.
