### ISSUE TITLE
Link in readme is incorrect

### ISSUE THREAD

**Issue by Banane9** [Yellow-Dog-Man/Locale#332]
>Formatting guide with examples (the C# version of the library currently doesn't implement all the formatters, but they will be added as needed): https://messageformat.github.io/messageformat/page-guide

This link in the Repository's readme leads to a 404. The correct link would appear to be https://messageformat.github.io/messageformat/ or https://messageformat.github.io/messageformat/guide/

**Comment by AwesomeTornado** [comment]
This issue can now be closed, fixed in PR #590 
Thanks for finding this!
