### ISSUE TITLE
English misses keys!

### ISSUE THREAD

**Issue by rampa3** [Yellow-Dog-Man/Locale#34]
Original en.json is missing the key Inventory.CreateDirectory.

**Comment by rampa3** [comment]
Also I found out there is no key for the Get URL button - might be hardcoded right now, since it has a label while there are no keys for it anywhere. If I find any more missing keys, they will be added here.

**Comment by ProbablePrime** [comment]
Your second issue has a fix submitted, I'll update locale soon.

**Comment by ProbablePrime** [comment]
https://github.com/Yellow-Dog-Man/Locale/pull/51 has the url string

**Comment by brodokk** [comment]
I should have added it here, there is a fix for the first one here https://github.com/Yellow-Dog-Man/Locale/pull/49
