### ISSUE TITLE
Hungarian [hu]

### ISSUE THREAD

**Issue by fernzhn** [Yellow-Dog-Man/Locale#399]
I am requesting for the hungarian [hu] language to be added as a translatable language! I'd be more than happy to help volunteering translating this game into Hungarian! ^^

**Comment by Banane9** [comment]
You can start it yourself too, all you need to do is going to your Resonite install folder, then Locale (with en.json, de.json, etc.).
Then copy paste the en.json and rename that file to hu.json and change the header as such:

```json
{
    "localeCode": "hu",
    "authors": ["fernzhn"],
    "messages": {
```

Then start translating the messages in the file as you want.

**Comment by Frooxius** [comment]
@Banane9 is correct. You just need to create a new locale file with your language and create PR to merge it in!

Once that's merged, it'll automatically generate on the list of languages here. You can also just put it in the Locales folder in Resonite and it'll automatically pick it up.

If there's anything else missing, say some fonts and such, you can request we add those too, though the default fonts should include majority of languages with latin based writing system.

**Comment by fernzhn** [comment]
My apologies 😅 
I thought I was supposed to open a ticket or so in order for me to be able to start it 😅 
Thank you for the help, I've started translating and looks like it will be a while until I can 100% this and upload it to here: D
I like how the text updates real time whenever I save the text filev though!

**Comment by stiefeljackal** [comment]
> My apologies 😅 I thought I was supposed to open a ticket or so in order for me to be able to start it 😅

It is good to mention your intent to create a new translation file via a GitHub issue. Once you do create the PR, you can always link this issue within the body of your PR by using [certain keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) (ex. Closes #SOMENUMBER).
