### ISSUE TITLE
Translator badge request

### ISSUE THREAD

**Issue by Zozokasu** [Yellow-Dog-Man/Locale#408]
I request translator badge.
I worked on translation such as https://github.com/Yellow-Dog-Man/Locale/pull/15, https://github.com/Yellow-Dog-Man/Locale/pull/28, https://github.com/Yellow-Dog-Man/Locale/pull/395, and so on.

User ID: U-Zozokasu

**Comment by Frooxius** [comment]
Added! Thank you!
