### ISSUE TITLE
Join button from Invite is broken

### ISSUE THREAD

**Issue by r7uaz0n** [Yellow-Dog-Man/Locale#431]
Received an invite to join world, but Join button is broken.   Unable to join world from invite:

![20240712104132_1](https://github.com/user-attachments/assets/3b48c576-99d6-40a1-9207-e4632f155830)

**Comment by Frooxius** [comment]
The Locale repo is not for reporting bugs with Resonite! 

You need to report issues here and follow our reporting guidelines: https://github.com/Yellow-Dog-Man/Resonite-Issues

**Comment by r7uaz0n** [comment]
whoops.  sorry.  First time.
