### ISSUE TITLE
Requesting translator badge

### ISSUE THREAD

**Issue by FoxoBread** [Yellow-Dog-Man/Locale#467]
### User ID

U-foxobread

**Comment by Frooxius** [comment]
Is the User ID correct? It doesn't seem to exist.

**Comment by XDelta** [comment]
Appears to be `U-FoxoBread`

**Comment by FoxoBread** [comment]
Ah it's case sensitive 😅
Yes, `U-FoxoBread`

**Comment by FoxoBread** [comment]
Any update on this? 😸

**Comment by Frooxius** [comment]
Added! Thanks for contributing!

Sorry it took a bit to get back to this.
