### ISSUE TITLE
Missing locale entry of Folder Importer

### ISSUE THREAD

**Issue by Zozokasu** [Yellow-Dog-Man/Locale#48]
![image](https://github.com/Yellow-Dog-Man/Locale/assets/13605108/4d7323a2-422c-4cf4-b6d2-771be612f81f)
There are no locale entries for
- Image slices as volumetric texture
- Image slices as volumeric texture (grayscale)

**Comment by ProbablePrime** [comment]
I've submitted a fix for this, I'll be adding it to locale shortly

**Comment by ProbablePrime** [comment]
https://github.com/Yellow-Dog-Man/Locale/pull/51 has the locale strings

**Comment by ProbablePrime** [comment]
This should be resolved now, please re-open if not
