### ISSUE TITLE
Update Guideline DON’T Rule to Include Upcoming Features and Team Member Branches

### ISSUE THREAD

**Issue by stiefeljackal** [Yellow-Dog-Man/Locale#505]
This issue was created in response to the closure of #504 due to the following reason:

> DON'T Submit strings from PRs that have the "New Strings" label until that PR is merged. The development team may need to update or change these strings as a part of their inclusion and this can cause conflicts. Wait till the PR is merged and THEN work on the new strings.

At the time of writing, the presence of a PR with the “New Strings” label for these particular strings does not exist. In fact, these new string keys only exist in the following branch: https://github.com/Yellow-Dog-Man/Locale/tree/Ryuvi/feat/TextureWizards .

It is completely understandable why the PR was closed since these keys are still in development. However, the rule as it stands does not make sense due to the absence of a PR with a “New Strings” tag.

Therefore, I recommend that this particular rule be amended to include something along the lines of “any upcoming features or team member branches” in addition to PRs with the “New Strings” tag. That way, this particular rule is clearer to those submitting.

**Comment by ProbablePrime** [comment]
Done: https://github.com/Yellow-Dog-Man/Locale/commit/d9b4f298511bdfe6f1d8e6ffe1a72f323e2a3f9b

**Comment by stiefeljackal** [comment]
@ProbablePrime Thank you.
