### ISSUE TITLE
Obscure settings related to "cuteness" use hardcoded text/untranslated locale keys

### ISSUE THREAD

**Issue by shny-scott** [Yellow-Dog-Man/Locale#509]
Various settings strings that are hidden by default either use locale keys with no localization in any languages or hardcoded text.

"I am cute" is hardcoded, and the header is entirely unlocalized.
![image](https://github.com/user-attachments/assets/13efa4af-117f-44ad-a339-8ebedfe7122c)

This entire description is hardcoded.
![image](https://github.com/user-attachments/assets/cd61456b-2561-47a6-a2dd-f15655fd3193)

While these are joke strings not intended to actually be seen by the public, the fact that a raw key and text in the wrong language can show up to end users seems like an oversight. The use of one locale key makes me think this was intended to be translatable at one point before the lazy way out was taken (possibly to keep it obscure? But then why leave the header as a key...).
(please don't patch this by simply removing the text entirely, it's funny and it helps me win internet arguments)

**Comment by XDelta** [comment]
Related response on Locale repo https://github.com/Yellow-Dog-Man/Locale/pull/323

**Comment by ProbablePrime** [comment]
We've made numerous changes to ensure this doesn't show up unless intended, If you're still seeing it, That's the bug and not that its not translated.

How are you finding it showing up?

**Comment by paradoxical-autumn** [comment]
You can still force it to show up once by spawning the `CutenessSettings` component into a world but the setting is removed upon restarting the game.

**Comment by JackTheFoxOtter** [comment]
That's gonna be a weird one to translate :D

**Comment by stiefeljackal** [comment]
> Related response on #323

Also related response https://github.com/Yellow-Dog-Man/Locale/pull/252

A translator felt it is best to not incorporate a translation for this key due to the fact that it is both a joke and meant for only one person. I do agree with this as well as the response in https://github.com/Yellow-Dog-Man/Locale/pull/323.

**Comment by Banane9** [comment]
> The use of one locale key makes me think this was intended to be translatable at one point before the lazy way out was take

The locale key is generated automatically by the settings system, it's not actively or intentionally being used

**Comment by Frooxius** [comment]
This is intentional.

This setting is just an easter egg, that's normally visible to only one person, end users should never see this unless it's forced, but even then it'll clean itself up next time.

We will not be adding locale strings for it, because it's not meant to be translated and seen.
