### ISSUE TITLE
Duplicate tool name keys (PR #553)

### ISSUE THREAD

**Issue by coolymike** [Yellow-Dog-Man/Locale#563]
In PR #553, several keys were added with the format `Tooltip.{Tool}.Name`. There's already keys for the same purpose under `Tools.Names.{Tool}`. Adding duplicate keys can lead to inconsistent translations. This can be seen with `en.json` where the existing key for the `PhysicalColliderSetter` tool exists as `Physical Collider Setter Tool`, and the new value is `Character Collider Setter Tool` (although many more small differences exist between the sets of keys).

<details>
<summary>Keys starting with <code>Tools.Names.</code> in en.json:</summary>
<pre>
{
  "Tools.Names.MultiTool": "Multi-Tool",
  "Tools.Names.CommonTools": "Common Tools",
  "Tools.Names.ManipulationTools": "Manipulation Tools",
  "Tools.Names.InformationTools": "Information Tools",
  "Tools.Names.GeometryLineBrush": "Geometry Line Brush Tool",
  "Tools.Names.Developer": "Developer Tool",
  "Tools.Names.ComponentClone": "Component Clone Tool",
  "Tools.Names.ProtoFlux": "ProtoFlux Tool",
  "Tools.Names.Material": "Material Tool",
  "Tools.Names.Glue": "Glue Tool",
  "Tools.Names.Light": "Light Tool",
  "Tools.Names.Shape": "Shape Tool",
  "Tools.Names.Microphone": "Microphone Tool",
  "Tools.Names.GrabbableSetter": "Grabbable Setter Tool",
  "Tools.Names.PhysicalColliderSetter": "Physical Collider Setter Tool",
  "Tools.Names.MeshVisibility": "Mesh Visibility Tool",
  "Tools.Names.CameraObjectVisibility": "Camera Object Visibility Tool",
  "Tools.Names.Color": "Color Tool",
  "Tools.Names.Mesh": "Mesh Tool",
  "Tools.Names.RiggedMeshTransfer": "Rigged Mesh Transfer Tool",
  "Tools.Names.Slicer": "Mesh Slicer Tool",
  "Tools.Names.ControllerDiagnostic": "Controller Diagnostic Tool",
  "Tools.Names.Measure": "Measure Tool",
  "Tools.Names.Label": "Label Tool"
}</pre></details>

<details>
<summary>Keys starting with <code>Tooltip.</code> and ending with <code>.Name</code> (now) in en.json:</summary>
<pre>
{
  "Tooltip.GeometryLineBrush.Name": "Geometry Line Brush",
  "Tooltip.Color.Name": "Color Tool",
  "Tooltip.GrabbableSetter.Name": "Grabbable Setter Tool",
  "Tooltip.CharacterCollider.Name": "Character Collider Setter Tool",
  "Tooltip.Light.Name": "Light Tool",
  "Tooltip.MeshVisibility.Name": "Mesh Visibility Tool",
  "Tooltip.Mesh.Name": "Mesh Tool",
  "Tooltip.Slicer.Name": "Object Slicer Tool",
  "Tooltip.Material.Name": "Material Tool",
  "Tooltip.Microphone.Name": "Microphone",
  "Tooltip.ProtoFlux.Name": "Proto-Flux Tool",
  "Tooltip.Meter.Name": "Meter Tool",
  "Tooltip.Glue.Name": "Glue Tool",
  "Tooltip.RigTransfer.Name": "Rig Mesh Transfer Tool",
  "Tooltip.ComponentClone.Name": "Component Clone Tool",
  "Tooltip.Shape.Name": "Shape Tool",
  "Tooltip.CameraObjectHider.Name": "Camera Object Hider Tool",
  "Tooltip.ControllerDiagnostic.Name": "Controller Diagnostic Tool",
  "Tooltip.Labeler.Name": "Labeler Tool"
}
</pre></details>

<details>
<summary>(Sorted) diff between those two, <code>&lt;</code> exists as <code>Tools.Names.{ToolName}</code>, <code>&gt;</code> exists as <code>Tooltip.{ToolName}.Name</code></summary>
<pre>
1c1,2
<  "Camera Object Visibility Tool",
---
>  "Camera Object Hider Tool",
>  "Character Collider Setter Tool",
3d3
<  "Common Tools",
6,7c6
<  "Developer Tool",
<  "Geometry Line Brush Tool",
---
>  "Geometry Line Brush",
10,11c9
<  "Information Tools",
<  "Label Tool"
---
>  "Labeler Tool"
13d10
<  "Manipulation Tools",
15,16d11
<  "Measure Tool",
<  "Mesh Slicer Tool",
19,23c14,18
<  "Microphone Tool",
<  "Multi-Tool",
<  "Physical Collider Setter Tool",
<  "ProtoFlux Tool",
<  "Rigged Mesh Transfer Tool",
---
>  "Meter Tool",
>  "Microphone",
>  "Object Slicer Tool",
>  "Proto-Flux Tool",
>  "Rig Mesh Transfer Tool",
</pre></details>

I created this issue to keep track of this as an open issue rather than closed PR.

Tagging @RueShejn as the creator of the mentioned PR, @Frooxius and @ProbablePrime as repository maintainers.

**Comment by Frooxius** [comment]
Thanks for catching this!

Hmm... We need to clean this up somehow. Going through the file, I think what we should do is:

- Rename all "Tooltips." and "Tooltip." to "Tool."
- Remove the "Tools.Names." versions - even though they're pre-existing, it kinda clashes with the naming scheme of other tool related strings

This way we'll have it unified using "Tool.<ToolType>" prefix for all the tool stuff. With each one having ".Name" for its actual name of the tool and then whatever other strings it needs.

I'll need a bit to sort this out, because we'll have to run a batch to rename all of these and update all the files.

**Comment by Frooxius** [comment]
Ok I've sorted this out: https://github.com/Yellow-Dog-Man/Locale/commit/c235329d239fb26cd9bb8489ded2d236504aba8f

Thank you again for the report!
