### ISSUE TITLE
Dummy == Dummy?

### ISSUE THREAD

**Issue by Jackalgirl** [Yellow-Dog-Man/Locale#75]
Quick question:

The instructions for the Locale files tell us:

> Always keep the "Dummy" : "Dummy" entry at the bottom of the file. This way you don't have to remember to remove the comma at the end of the last entry every time

I take the important thing here is that the last line the "messages" section, being a comma-separated, list of stuff, can't have a comma after it (because it's the end of the list), so if you're going to add anything (such as missing lines from the Resonite update), add it before the "Dummy" : "Dummy" line, so you don't have to worry about it.

However, there's some thought that the line has to remain *exactly the way it is* -- that is, we're not to provide the translation for the word "dummy"; we have to leave the translation as "dummy" in every language.  I've checked other files, including ones that do not use a Latin character set, and they all say "Dummy": "Dummy" as the last line.

Are we doing to break something if we provide a translation, or is the important point here that it just can't have a comma after it (if it's the last line of the "messages" section)?

Thank you in advance!

**Comment by Jackalgirl** [comment]
Like, we could all change the list line to read:

"Dummy" : "Cheese" 

(in our respective languages) and it would work fine.

**Comment by ProbablePrime** [comment]
Its not used in our codebase, just leave it as is. It is not used.

Its there to prevent JSON based issues with those more unfamiliar with JSON.

**Comment by Jackalgirl** [comment]
Awesome, thank you!
