### ISSUE TITLE
Tool Locales

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Locale#89]
I was made aware by @Psychpsyo that the translated tool names we decided on weren't actually showing in-game. I took that as an opportunity to go through all tools. Here's what I found:

Equip names of all tools aren't using locale strings

Missing loceles on Individual tools:
- Dev Tool:
  - "Selection: Single / Multi"
  - "Interaction: Projection / Tip"
- Component Clone Tool:
  - "Single Instance: On / Off"
  - "Clear Template"
- Glue Tool
  - Alle 3 mode options
- Light Tool
  - "Change Color"
  - "Shadows: None / Hard / Soft"
- Rig Mesh Transfer Tool
  - "Clear Source"
- Meter Tool
  - "Measure in World / Object Space"
  - "Two / Multiple Points"
  - "Mode: Ray / Perpendicular / Drag"
- Module Snapping Tool
  - All texts 
  - Has no equip name
- Multi Tool
  - All Texts
  
  @ProbablePrime for general tool locales
  @RyuviTheViali for Module Snapping Tool
  @Aegis_Wolf for Multitool

**Comment by ProbablePrime** [comment]
I'll take a look
