### ISSUE TITLE
en.json: should all error messages that advise to contact support include the support url?

### ISSUE THREAD

**Issue by Muppeq** [Yellow-Dog-Man/Locale#91]
Some of the new error messages don't show the url:
        "Login.MalformedUID.Description": "Try reinstalling, or contact support.",
(and the next three)

but others include it:        
        "Login.DuplicateAccount.Description": "Please contact support at support.resonite.com",

**Comment by ProbablePrime** [comment]
Yes they should, feel free to PR this. Thank you!!

**Comment by Muppeq** [comment]
fixed in #106
